### ISSUE TITLE
Discrete FPID Block in Simulink

### ISSUE THREAD

**Issue by glasachin** [AlekseiTepljakov/fomcon-matlab#1]
Hi,
    I was using Discrete Fractional PID block in my simulink model for controlling a plant. Once I used the pre given values then results are OK. But when I use GA algorithm to optimize it's parameters then Discrete Fractional PID block doesn't work as per expectation and it gives different result even on the previous values.
When I delete the block and use new block it again give correct values and this loop continues....

Please have a look into this issue. I can even show you the problem through skype or some other mean.

Looking forward to hear from you.

With Regards
Sachin Sharma

**Comment by extall** [comment]
Hi, please describe your use case more fully. Are you using the GA algorithm for offline tuning? Or are you trying to achieve tuning online?

**Comment by extall** [comment]
No comments for more than a year - closing.
