### ISSUE TITLE
Fractional order transfer function

### ISSUE THREAD

**Issue by Anikesh31** [AlekseiTepljakov/fomcon-matlab#2]
Is there a way to pass the transfer function parameters via command window or a m file? As of now, I can't write a variable in the block, unlike the regular Simulink transfer function block.

**Comment by extall** [comment]
Yes, there is. You have to know the parameter name, though. For this, right click the block of interest, choose ‘Mask → View Base Mask...’ and locate the ‘Parameters & Dialog’ tab.

Here's an example. Suppose you have a model ‘test’ and inside it a Fractional Transfer Fcn block name ‘My transfer fcn’. Then, the code `set_param('test/My transfer fcn', 'zeroPoly', '1+s')` will set the zero polynomial string to ‘1+s’.

Hope this works for you. Also, if you prefer to set factors/orders via vectors, there is a ‘Num Fractional Transfer Fcn’ block available in the fod model set.

**Comment by Anikesh31** [comment]
Dear Aleksei,

Thanks a lot for your prompt reply.

Regards,
Anikesh Kumar

**Comment by pulak258** [comment]
I was facing the similar issue when I try to pass the variable from m-file to fractional transfer function block. I followed your suggestion to modify the using following code [set_param('m1/FOIMC', 'zeroPoly', '(1-0.25*kp)*s+kp')] and [set_param('m1/FOIMC', 'polePoly', 'lambda*s^a+1')]. I was able to create the variable inside the Frac Tf(s) block. 
But when I run the model it is still showing the error as [undefined function or variable 'kp']

![get](https://user-images.githubusercontent.com/75560199/101274390-a9b08380-37c3-11eb-9b5a-046ea73769ba.jpg)

**Comment by mvipul77** [comment]
Error is not resolved by given answers above , it still says "invalid setting in fractional transfer function block (mask) for parameter zeropoly"

**Comment by extall** [comment]
Please check the way you set the parameter and whether Simulink can resolve the parameter that you set from its own workspace or the global one.
