### ISSUE TITLE
Frac tf(s) in Simulink does not access workspace

### ISSUE THREAD

**Issue by PCYCAP** [AlekseiTepljakov/fomcon-matlab#21]
It does not seem possible to enter parameters in a Frac tf(s) object in Simulink that have been defined in the Matlab workspace. Please advise.

**Comment by extall** [comment]
Please provide a more detailed use case example. What are you trying to achieve?

**Comment by PCYCAP** [comment]
Thanks for the quick response. I want to be able to specify parameters in my Matlab workspace to be used in the Frac tf(s) object in Simulink. In this way, I can specify any values for the object in Matlab and then simulate For example, I might want to use this is an optimizations set-up.

**Comment by extall** [comment]
Ok, yes, you are correct. Currently, variables inserted into the FOMCON Simulink blocks' dialogues are not actually evaluated to take the values from the base workspace. Nice catch! I would also expect this to work, but it does not, and I wonder why nobody noticed before.

I file this as a bug. Meanwhile, there is a way to accomplish what you want to do, it just takes a bit more effort. The solution is to use `set_param`. I will record a quick screencast where I will show you how this works.

**Comment by PCYCAP** [comment]
Thanks again and I look forward to seeing the screencast. Can I say that your Toolbox looks like it is a valuable resource and I  congratulate you on its development.

**Comment by extall** [comment]
The video is here: https://youtu.be/77FCaMrZ9_o
I was reviewing it and it seems if you hover over the textbox in the dialog, it will show you the name of the variable.

![Screenshot 2023-04-12 150213](https://user-images.githubusercontent.com/18900943/231451111-d2519ec9-5730-4e39-9ed2-a0f37b2b8b4d.png)

But it doesn't hurt to know how the mask is implemented as well :)

**Comment by PCYCAP** [comment]
Many thanks! You prepared the video very quickly and it looks like a good temporary solution to my problem, for which I am most grateful. I look forward to downloading the updated Toolbox when this bug fixed.

**Comment by PCYCAP** [comment]
Unfortunately, my assumption that your suggestion solved my problem was premature. If one wished to use the Frac tf(s) Simulink object in, for example, a 'lsqnonlin' optimization computation, then the parameter values in the expression tf_den= 's^1.5+s^0.1+2' would have to be repeatedly and automatically updated before calling 'sim_model_example.slx' within the associated optimization function. I cannot see how this would not be possible in an expression such as 's^1.5+s^0.1+2' but you may have a suggestion. I thought it best to bring this to your attention before you did the bug fix.

**Comment by extall** [comment]
Fortunately, for this there is already a solution. Use `fod_v2.slx` library, it has Tf blocks that support numerical values to describe the polynomials.

**Comment by extall** [comment]
Besides that, you can consider using the `fpoly2str` function to convert numerical vectors to a string representation.

**Comment by extall** [comment]
Upon further investigation, it seems the `Fractional Transfer Fcn` might be the only block that suffers from the present issue. In other blocks, you can easily use variables from the workspace, including the above mentioned `Num Fractional
Transfer Fcn` in `fod_v2.slx`.

**Comment by extall** [comment]
Upon further investigation, it seems the `Fractional Transfer Fcn` might be the only block that suffers from the present issue. In other blocks, you can easily use variables from the workspace, including the above mentioned `Num Fractional
Transfer Fcn` in `fod_v2.slx`.

**Comment by extall** [comment]
Upon even further investigation, it seems that this is not really a bug, but the way this specific function was designed! The reason is that if we have a conflicting `eval` due to the input being a string. What I mean by that is if we eval something like `1+s^0.5` in the base workspace, the only case when it will work is if in the same workspace a variable `s` is defined as `s=fotf('s')`, however, that would be really confusing.

Hence, it turns out this is not a bug! If you want tunable parameters, please only use blocks that support numerics, again, like the `Num Fractional Transfer Fcn` in the above example.

**Comment by PCYCAP** [comment]
Thanks again. I am really sorry to bother you again but I still require advice if you have time to provide it. 
I have looked at the  fod_v2.slx library and tried using the Frac Tf block again. However, I still encounter similar problems which are mainly because 's' still appears to be required for the polynomials and Matlab can only transmit this from the workspace to the Simulink Bloch within quotes. If so, the parameter values cannot be included. 
If you might send me some specific coding that would resolve this problem, for example how the set_param functions should be specified to include numerical values for the parameters, I would be most grateful.

**Comment by PCYCAP** [comment]
I have resolved the problem by building the model with fractional integrators and gains but I would still like to know how to handle the full transfer functions, as requested in my last comment, if you can help me.

**Comment by extall** [comment]
Please confirm that your approach is not working with `Num Fractional Transfer Fcn`.

**Comment by PCYCAP** [comment]
Unfortunately, I have had no success using the Simulink objects in  fod_v2.

The problem with 'Frac tf(s)' is that, unlike the fractional integrator, it will not accept letters defined by specified values in the workspace; it will only accept the parameter values. Without this, one cannot use it with a lsqnonlin routine to optimize the model parameters.

Although building the model using 'fractional integrators' and gains appears to work with parameters set by letters defined in the workspace, it still does not appear to work with 'lsqnonlin' optimization, even when the parameters being defined by 'lsqnonlin' are set as global vales so the Simulink model should be seeing and using these as they are updated. 

Of course these problems  may well be something I am doing wrong but I have tried everything I can think of and, unless you have any further suggestions, I am afraid will have to give up. 

If you do not have any solution I am, in any case, very grateful for all your previous assistance which has taught me what one can and cannot do with your Toolbox routines. It is certainly very useful for fractional TF simulation but, unless you have any further comments about working with an optimization routine such as 'lsqnonlin', it does not seem yet to have this capability. I hope my comments may have assisted you in this connection.
