### ISSUE TITLE
MATLAB fcn using oustaloup approximation doesn't work

### ISSUE THREAD

**Issue by tahar96nouaoui** [AlekseiTepljakov/fomcon-matlab#23]
![image_2024-05-27_145413267](https://github.com/extall/fomcon-matlab/assets/100046207/346e1d0b-c45f-4214-9050-5f45fe077254)
Hello everyone
Im trying to implement a fractional integrator for processor in the loop simulation in MATLAB, but the software and the card i am using only supports data of type single, which fomcon fractional integrator does not provide, to solve this, i tried using the approximation of oustaoup inside a MATLAB fcn block in simulink, I've managed to make the simulation run, but the output of the fractional integrator is a constant negligible value which nowhere close to the output of the fractional integrator block.

**Comment by extall** [comment]
The issue cannot quite be categorized as a FOMCON issue or a feature request, so closing it. If you want a feature that FOMCON does not currently provide, please open a separate issue.
