### ISSUE TITLE
Fractional PID results not as intended

### ISSUE THREAD

**Issue by sarahToonsi** [AlekseiTepljakov/fomcon-matlab#3]
Im trying to work with the toolbox with a water tank system to test my fractional PI controller. It was producing weird results and even when I tried to test it with an integer pi by setting lambda=1 I dont get the same behavior that I get with my integer PI. I assume there is some problem in the fractional integration that I cant figure out. I need help

**Comment by extall** [comment]
When you open an issue, please provide relevant details. Otherwise I cannot reproduce the problem you're experiencing.
