### ISSUE TITLE
Model Identification 

### ISSUE THREAD

**Issue by Anikesh31** [AlekseiTepljakov/fomcon-matlab#4]
Is there a way in the FOMCON toolbox to directly identify a non-commensurate fractional order model of a given structure not necessarily with unity gain from a given higher order integer model i.e. without resorting to any input-output data?

**Comment by serkan1717** [comment]
In matlab coding i have a problem. When i try to code like following, i came across the fault. In PID control there is no problem like this. Can you guess where problem is? Thank you very much. 

```

> %Defining of Input and output of plant
> plant.InputName='e';
> plant.OutputName='y';
> 
> %Defining of Input and output of system1
> Pfes.InputName='y';
> Pfes.OutputName='fes';

```

ERROR:No public property InputName exists for class fotf.

Error in FOPID_new (line 79)
plant.InputName='e';

**Comment by extall** [comment]
I cannot guess what the problem is because what you cite here has nothing to do with FOMCON.
