### ISSUE TITLE
Issue with Fractional PI Controller

### ISSUE THREAD

**Issue by wadyan** [AlekseiTepljakov/fomcon-matlab#5]
Hi

I have noticed that the command isstable(SYS) always showing zero for the fractional PI controller, which means that the system is unstable. 

I have changed the open-loop and closed-loop transfer functions with many others, and I have optimized the fractional exponent. However, every time I run that command, it shows me an unstable system!

Even if I plot the response for 100000 seconds, it shows me a perfect response without any oscillation or divergence!

I think that there is an issue with the fractional PI controller. Also, the following unsolved issue emphasizes my point about the fractional PI controller:
https://github.com/extall/fomcon-matlab/issues/3

Thanks

**Comment by extall** [comment]
Simple exercise without using FOMCON:
`s=tf('s'); isstable(1+1/s)`
What is the answer?

**Comment by wadyan** [comment]
I made a program to create random feedback transfer functions.

I have examined this particular type (FPI) with a huge number of virtual systems. All the controllers (P, PI, PD, PID, FPD, and FPID) give feasible optimal stable designs; except FPI?! It always shows "not stable" for any given closed-loop transfer function!!
