### ISSUE TITLE
Solver for Fractional Order System

### ISSUE THREAD

**Issue by anusha211198** [AlekseiTepljakov/fomcon-matlab#6]
Sir, 

I wanted to check which fixed-step size solver would be appropriate for using FOMCON. The ones mentioned in your paper are variable step size and would not be applicable to my code. 

I have tried running the code with ODE-4 Runge-Kutta, however, that results in an error.

**Comment by extall** [comment]
This also depends on the system that you are trying to simulate. There are examples of non-fractional models which cause problems for the solvers, but with fractional calculus analyzing the specific situation becomes critical.

Still, for completeness, please reproduce the error that you are receiving.

**Comment by anusha211198** [comment]
Derivative of state '1' in block 'fractional_controller/Fractional integrator5/Transfer Fcn1' at
time 61.355019239157059 is not finite. The simulation will be stopped. There may be a singularity
in the solution.  If not, try reducing the step size (either by reducing the fixed step size or
by tightening the error tolerances)

This is with ODE15s

**Comment by extall** [comment]
Alright, what is the value of the fractional power?

**Comment by anusha211198** [comment]
Sir, 

I am trying to optimize the fractional order during the simulation. There are a total of 12 parameters being optimized, out of which four are the fractional orders (2 for differentiator and 2 for integrator).

**Comment by extall** [comment]
You should limit the search space for fractional powers.

**Comment by anusha211198** [comment]
I have given the range for all as 0-1. I'm not sure how much I should limit these powers

**Comment by extall** [comment]
Were you able to solve this? If yes, please provide insight.

**Comment by extall** [comment]
Seems like there is no further development here, closing.
