### ISSUE TITLE
fomcon version problem

### ISSUE THREAD

**Issue by denniskao872** [AlekseiTepljakov/fomcon-matlab#7]
I have a motor control block only use on matlab 2012a to control it. Is there have a  lowest version to cover the 2012a matlab?

**Comment by extall** [comment]
In other words, you need the `fod_v2.mdl` library for an older version of MATLAB? Find a version for R2012b attached. Hopefully, it will work for you.

[fod_v2_R2012b.zip](https://github.com/extall/fomcon-matlab/files/6419895/fod_v2_R2012b.zip)

General comment: unfortunately, Mathworks have never really cared about backwards compatibility. As a developer, it is not feasible for me to keep a stack of MATLAB releases in my development environment. I typically use a MATLAB version that is about 2 years old and gradually upgrade to keep at least +/- 2 years of compatibility with my releases. So, the functionality/compatibility of FOMCON toolbox also follows that trend.
